language: node_js
node_js:
  - 0.12
  - 4.0
  - 4.1
  - 4.2
  - 5.0
  - node
matrix:
  fast_finish: true
  allow_failures:
    - node_js: node
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  slack:
    secure: UYwnLYQ+Zt3BGQpYg4uWcbI8cs5+iWh1CWyvrMkYsnJ5vnyuF02kNWhpegawFqy6O0rEbOPcvgw+rsmr2a7x7SIHQ4Ej19rnbIHZEGJDJwd636FnCLzzS9m1fwmAa2cbIa0VufzTyrJwiibC05l31J9/mfSXwo7yZEmPahmlstU=
